service: cndp-event-sourcing

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - Table
          - Arn
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource:
        Fn::GetAtt:
          - Stream
          - Arn

functions:
  command:
    handler: handler.command
    environment:
      TABLE_NAME:
        Ref: Table
  trigger:
    handler: handler.trigger
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - Table
              - StreamArn
          batchSize: 100
          startingPosition: TRIM_HORIZON
    environment:
      STREAM_NAME:
        Ref: Stream

package:
  exclude:
    - node_modules/**
    - '!node_modules/highland/**'
    - '!node_modules/util-deprecate/**'
    - '!node_modules/uuid/**'

resources:
  Resources:
    Stream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${opt:stage}-${self:service}-stream
        RetentionPeriodHours: 24
        ShardCount: 1
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}-${self:service}-t1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
